# fly.toml app configuration file generated for t2-fly-nis-geomanager-morning-feather-167 on 2025-02-07T02:40:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 't2-fly-nis-geomanager-morning-feather-167'
primary_region = 'cdg'
console_command = '/code/manage.py shell'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'python manage.py migrate --noinput'
  release_command_timeout = "5m"  # Increase from default

[env]
  DJANGO_SETTINGS_MODULE = 'sandbox.settings.production'
  PORT = '8000'
  PYTHONPATH = '/app'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
