services:
  # Backend service (Geomanager)
  - type: web
    name: geomanager-backend
    env: docker
    plan: standard
    image: ${GAR_HOSTNAME}/${PROJECT_ID}/${REPOSITORY}/geomanager:latest
    region: oregon
    healthCheckPath: /admin/login/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: geomanager-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: sandbox.settings.production
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: GAR_HOSTNAME
        value: [REGION]-docker.pkg.dev
      - key: PROJECT_ID
        value: [YOUR-PROJECT-ID]
      - key: REPOSITORY
        value: [YOUR-REPOSITORY-NAME]
    disk:
      name: geomanager-data
      mountPath: /app/media
      sizeGB: 10

