{pkgs}: {
  deps = [
    pkgs.pgadmin4
    pkgs.chromedriver
    pkgs.arrow-cpp
    pkgs.libffi
    pkgs.glib
    pkgs.gdk-pixbuf
    pkgs.freefont_ttf
    pkgs.libcxx
    pkgs.rustc
    pkgs.openssl
    pkgs.libxcrypt
    pkgs.libiconv
    pkgs.cargo
    pkgs.glibcLocales
    pkgs.cacert
    pkgs.libgeotiff
    pkgs.zlib
    pkgs.netcdf
    pkgs.libjpeg
    pkgs.hdf5
    pkgs.curl
    pkgs.postgis
    pkgs.postgresql
    pkgs.geos
    pkgs.proj
    pkgs.gdal
    pkgs.tk
    pkgs.tcl
    pkgs.qhull
    pkgs.pkg-config
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.freetype
    pkgs.ffmpeg-full
    pkgs.cairo
    pkgs.yarn
  ];
}